### ISSUE TITLE
Unable to find releases on Bandcamp, failed obtaining ID

### ISSUE THREAD

**Issue by gamoeri** [snejus/beetcamp#33]
I'm having trouble using the bandcamp plugin. I persistently get this error.

`Enter release ID: https://ltdwlbl.bandcamp.com/album/ltdwlbl008
bandcamp: Failed obtaining https://ltdwlbl.bandcamp.com/album/ltdwlbl008
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/beetsplug/bandcamp/__init__.py", line 275, in handle
    return call()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/beetsplug/bandcamp/_metaguru.py", line 457, in album
    return self.albuminfo(include_all)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/beetsplug/bandcamp/_metaguru.py", line 406, in albuminfo
    _tracks = [self._trackinfo(track, medium_total) for track in filtered_tracks]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/beetsplug/bandcamp/_metaguru.py", line 406, in <listcomp>
    _tracks = [self._trackinfo(track, medium_total) for track in filtered_tracks]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/beetsplug/bandcamp/_metaguru.py", line 374, in _trackinfo
    **self._common,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/beetsplug/bandcamp/_metaguru.py", line 354, in _common
    artist_id=self.artist_id,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/beetsplug/bandcamp/_metaguru.py", line 187, in artist_id
    return self.meta["byArtist"]["@id"]
KeyError: '@id'
No matching release found for 1 tracks.
`

Secondly, I calso can't get the beetcamp cmd line to work : 
`-bash: beetcamp: command not found`
Even if I have installed it using pip. 

Help would be appreciated. Thanks!

**Comment by snejus** [comment]
Thanks for reporting this! I will look into this ASAP. Could you confirm which version is being used? Outputs from the following commands would also be useful, especially regarding it not being found in the path:

```sh
echo $PATH
which -a beet beetcamp
pip list
```

Thanks for taking your time to report it!

**Comment by snejus** [comment]
Hmm I've tried reproducing it but it worked fine with `beetcamp 0.15.1`. @gamoeri if you could run the commands above and share the output it would help a lot to pinpoint the problem.

**Comment by gamoeri** [comment]
Hello thanks for your answer! 
**echo $PATH**
`/Users/erigamo/.nvm/versions/node/v14.15.1/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

**which -a beet beetcamp**
```
/Library/Frameworks/Python.framework/Versions/3.10/bin/beet
/Library/Frameworks/Python.framework/Versions/3.10/bin/beet
/usr/local/bin/beet
```

**pip list**
```
Package                Version
---------------------- ---------
aubio                  0.4.9
beetcamp               0.7.1
beets                  1.5.0
beets-bpmanalyser      1.3.3
cached-property        1.5.2
certifi                2021.10.8
charset-normalizer     2.0.9
confuse                1.6.0
idna                   3.3
jellyfish              0.8.9
mediafile              0.8.1
munkres                1.1.4
musicbrainzngs         0.7.1
mutagen                1.45.1
numpy                  1.23.1
oauthlib               3.1.1
packaging              21.3
pip                    22.2.1
pycountry              20.7.3
pyparsing              3.0.9
python-dateutil        2.8.2
python3-discogs-client 2.3.12
PyYAML                 6.0
requests               2.26.0
setuptools             57.4.0
six                    1.16.0
Unidecode              1.3.2
urllib3                1.26.7
wheel                  0.37.1
```

**Comment by snejus** [comment]
hey, thanks for this! You are running a fairly ancient version of it! :) try `pip install -U beetcamp`. It should upgrade it for you :)

**Comment by gamoeri** [comment]
Worked! Thanks!

**Comment by snejus** [comment]
Enjoy!
