### ISSUE TITLE
`AssertionError: Failed to find a release under the given url` for `https://palindromeaustria.bandcamp.com/album/bundle-these-last-scattered-synapses-3`

### ISSUE THREAD

**Issue by mkhl** [snejus/beetcamp#44]
Running `~/.local/pipx/venvs/beets/bin/beetcamp https://palindromeaustria.bandcamp.com
/album/bundle-these-last-scattered-synapses-3` results in an assertion error:

> ```
> bandcamp: Failed obtaining singleton from https://palindromeaustria.bandcamp.com/album/bundle-these-last-scattered-synapses-3
> Traceback (most recent call last):
>   File "/home/mkhl/.local/pipx/venvs/beets/bin/beetcamp", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/mkhl/.local/pipx/venvs/beets/lib/python3.11/site-packages/beetsplug/bandcamp/__init__.py", line 367, in main
>     raise AssertionError("Failed to find a release under the given url")
> AssertionError: Failed to find a release under the given url
> ```

I assume something's going wrong scraping data from the site?

**Comment by snejus** [comment]
Thanks for reporting this! Let me look into it

**Comment by snejus** [comment]
`beetcamp` has this logic that skips parsing media formats that have **Bundle** in their name - I forgot to consider the case where **Bundle** may be part of the album name 🤦🏽‍♂️ . Will get this fixed today!

**Comment by snejus** [comment]
This should be fixed now :)

**Comment by mkhl** [comment]
It is indeed, thanks for the quick fix! :)
