### ISSUE TITLE
Package 'requests' still a dependency

### ISSUE THREAD

**Issue by tillmann** [snejus/beetcamp#71]
Hi! 
I just stumbled upon this and wanted to let you know. beetcamp CLI and the beets plugin fail when package `requests` is not installed:

```
** error loading plugin bandcamp:
Traceback (most recent call last):
  File "/root/.local/lib/python3.12/site-packages/beets/plugins.py", line 269, in load_plugins
    namespace = __import__(modname, None, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/beetsplug/bandcamp/__init__.py", line 31, in <module>
    from beetsplug import fetchart  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/beetsplug/fetchart.py", line 24, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

This is the case when I install beetcamp using pip.

This is the cause, I guess: 
https://github.com/snejus/beetcamp/blob/20efda7bb7eee8ed68b4856242d917c634c0234b/beetsplug/bandcamp/__init__.py#L31

I don't know poetry so I am not sure if there is a way to install beetcamp "correctly" but at least, if there is a correct way, then it could be mentioned in the Readme.md. :) Installing requests of course fixes the problem.

**Comment by tillmann** [comment]
Just saw this. https://github.com/snejus/beetcamp/issues/66#issuecomment-2382744892 so it is no news to you. Apologies for the noise. Please close as you see fit.

**Comment by snejus** [comment]
Thanks for reporting! The fix has been merged but not released yet :)
